name: Deploy Sauna Page

on:
  push:
    branches:
      - main  # Vagy 'master', amit haszn√°lsz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insert API Key
        run: |
          sed -i "s/___THINGSPEAK_API_KEY_PLACEHOLDER___/${{ secrets.THINGSPEAK_KEY }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
