name: Deploy Protected Sauna Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insert API Key
        run: |
          sed -i "s/REPLACE_ME/${{ secrets.THINGSPEAK_KEY }}/g" index.html

      - name: Encrypt index.html with Staticrypt
        env:
          PASSWORD: ${{ secrets.WEB_PASSWORD }}
        run: |
          # 1. Letakarítjuk a korábbi próbálkozások maradványait
          rm -rf encrypted
          rm -f temp.html
          
          # 2. Titkosítás - itt a titok: a --short engedi a rövid jelszavadat
          # Azonnal az index.html-be mentünk, így nem kell az 'mv' parancs
          npx staticrypt index.html -p "$PASSWORD" --short --shorten -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
