name: Deploy Protected Sauna Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insert API Key
        run: |
          # Behelyettesítjük az API kulcsot a main ágról érkező fájlba
          sed -i "s/REPLACE_ME/${{ secrets.THINGSPEAK_KEY }}/g" index.html

      - name: Encrypt index.html with Staticrypt
        env:
          PASSWORD: ${{ secrets.WEB_PASSWORD }}
        run: |
          # 1. Töröljük a zavaró mappákat
          rm -rf encrypted
          
          # 2. Titkosítunk egy ÚJ, ideiglenes fájlba (temp.html)
          # A --short és -p "$PASSWORD" kezelik a rövid jelszót
          npx staticrypt index.html -p "$PASSWORD" --short --shorten -o temp.html
          
          # 3. Kicseréljük az eredetit az új titkosítottra
          mv temp.html index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true # Ez kényszeríti a GitHubot, hogy az új, titkosított verziót mutassa
