name: Deploy Protected Sauna Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insert API Key
        run: |
          # Először behelyettesítjük az API kulcsot a fájlba
          sed -i "s/REPLACE_ME/${{ secrets.THINGSPEAK_KEY }}/g" index.html

      - name: Encrypt index.html with Staticrypt
        env:
          PASSWORD: ${{ secrets.WEB_PASSWORD }}
        run: |
          # A --short engedi a rövid jelszót
          # Az -o index.html kényszeríti, hogy a fő fájlt írja felül, ne mappát hozzon létre
          npx staticrypt index.html -p "$PASSWORD" --short --shorten -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
