name: Deploy Protected Sauna Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insert API Key
        run: |
          # Behelyettesítjük az API kulcsot a main ágról érkező fájlba
          sed -i "s/REPLACE_ME/${{ secrets.THINGSPEAK_KEY }}/g" index.html

      - name: Encrypt index.html with Staticrypt
        env:
          PASSWORD: ${{ secrets.WEB_PASSWORD }}
        run: |
          # 1. Letakarítjuk a korábbi hibás mappákat
          rm -rf encrypted
          
          # 2. Titkosítás:
          # --short: engedi a 14 karakternél rövidebb jelszót
          # --shorten: rövidebb URL-t generál
          # -o index.html: közvetlenül a főoldalt írja felül, nem mappát csinál
          npx staticrypt index.html -p "$PASSWORD" --short --shorten -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true # Ez kényszeríti a GitHubot, hogy az új, titkosított verziót mutassa
